services:
  postgres:
    image: postgres:15-alpine
    container_name: nexustracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nexustracker
      POSTGRES_USER: nexustracker_user
      POSTGRES_PASSWORD: nexustracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nexustracker-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexustracker-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexustracker.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nexustracker-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  nexustracker-network:
    driver: bridge 